### ISSUE TITLE
Specify Dependencies

### ISSUE THREAD

**Issue by mush42** [apptek/ArabicDiacritizationInterspeech2023#1]
Hi,

Would you mind providing the exact versions of packages used in the paper to aid in reproducibility.

I tried using the latest version of `returnn` but it always fails with an error.

Thanks in advance.

Best
Musharraf

**Comment by JackTemaki** [comment]
Hi Musharraf,

thanks for being interested in this work.

The base dependencies of RETURNN (https://github.com/rwth-i6/returnn/blob/master/requirements.txt) + any remotely recent version of Tensorflow (>2.3) should be sufficient. We do not give exact versions as compatibility (of Tensorflow) may vary with your operating system, available GPU and available CUDA version.

**Comment by mush42** [comment]
@JackTemaki

This is the error I face when running the training command:

```bash
python3 returnn/rnn.py configs/config_2SDiac.py
```

The error:

```bash
  File "configs/config_2SDiac.py", line 575, in <module>
    line: input_time = DimensionTag(kind=DimensionTag.Types.Spatial, description="input time")
    locals:
      input_time = <not found>
      DimensionTag = <local> <class 'returnn.tensor.dim.Dim'>
      kind = <not found>
      DimensionTag.Types = <local> <class 'returnn.tensor._dim_extra.DimTypes'>
      DimensionTag.Types.Spatial = <local> <spatial>
      description = <not found>
TypeError: Dim.__init__() missing 1 required positional argument: 'dimension'
```

**Comment by JackTemaki** [comment]
It seems that indeed there was a breaking change in RETURNN with respect to the DimensionTag API.

You can use the commit with id 3ec35ceaf3b0268445068ff1b807824b401d613f.
